apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: argocd # Namespace where the Argo CD Application resource lives
spec:
  project: default # The Argo CD Project this application belongs to
  source:
    repoURL: https://github.com/vamsi-mr/argocd-eks.git # URL of the Git repository
    targetRevision: main # The specific branch, tag, or commit to sync from
    path: namespaces # The path within the repository where the application manifests are located
  destination:
    server: https://kubernetes.default.svc # The API server URL of the target Kubernetes cluster
    namespace: argocd # The namespace in the target cluster where the application will be deployed
  syncPolicy:
    automated: # Enable automated synchronization
      prune: true # Delete resources that are no longer in Git
      selfHeal: true # Revert changes made manually in the cluster to match Git
    syncOptions:
      - CreateNamespace=true # Automatically create the target namespace if it doesn't exist