### ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name : cart
  namespace: roboshop
  labels: 
    component: cart
    project: roboshop
    tier: app
data:
  REDIS_HOST: "redis" 
  CATALOGUE_HOST: "catalogue" 
  CATALOGUE_PORT: "8080"

---
### Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  ## deployment labels
  labels:
    component: cart
    project: roboshop
    tier: app
spec:
  replicas: 1
  ## these are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      component: cart
      project: roboshop
      tier: app
  ## This is pod definition
  template:
    metadata:
      labels:
        component: cart
        project: roboshop
        tier: app
    spec:
      containers:
      - name: cart
        image: 025523569021.dkr.ecr.us-east-1.amazonaws.com/roboshop/cart:1.0.0
        envFrom:
        - configMapRef:
            name: cart

---
### Service
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
  labels:
    component: cart
    project: roboshop
    tier: app
spec:
  selector:
    component: cart
    project: roboshop
    tier: app
  ports:
    - protocol: TCP 
      port: 8080  ## service port
      targetPort: 8080  ## container port
      