### ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name : shipping
  namespace: roboshop
  labels: 
    component: shipping
    project: roboshop
    tier: app
data:
  CART_ENDPOINT: "cart:8080" 
  DB_HOST: "mysql"

---
### Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  ## deployment labels
  labels:
    component: shipping
    project: roboshop
    tier: app
spec:
  replicas: 1
  ## these are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      component: shipping
      project: roboshop
      tier: app
  ## This is pod definition
  template:
    metadata:
      labels:
        component: shipping
        project: roboshop
        tier: app
    spec:
      containers:
      - name: shipping
        image: 025523569021.dkr.ecr.us-east-1.amazonaws.com/roboshop/shipping:1.0.0
        envFrom:
        - configMapRef:
            name: shipping

---
### Service
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
  labels:
    component: shipping
    project: roboshop
    tier: app
spec:
  selector:
    component: shipping
    project: roboshop
    tier: app
  ports:
    - protocol: TCP 
      port: 8080  ## service port
      targetPort: 8080  ## container port
